parameter[:getter] option
rswag/rswag pull request #605
Opened 2023-03-07 00:06 UTC by pechorin

## Problem
Adopted pull request https://github.com/rswag/rswag/pull/436
Fix known issue: conflict with rspec default matchers include https://github.com/rswag/rswag/issues/188 (and also with status method)

## Solution
Add support for :getter parameter option to explicitly define custom param getter method and avoid rspec conflicts with include matcher and status method

### This concerns this parts of the OpenAPI Specification:
-

### The changes I made are compatible with:
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

### Related Issues
https://github.com/rswag/rswag/issues/188 

### Checklist
- [ ] Added tests
- [ ] Changelog updated
- [ ] Added documentation to README.md

### Steps to Test or Reproduce
-

2023-03-07 11:16 UTC, NastyaPatutina approved these changes

2023-03-07 11:17 UTC, TruesSpeak approved these changes

2023-03-09 12:03 UTC, pechorin commented
Hello @jtannas, can you please look at this PR? Maybe this is still worked solution for rswag?

2023-03-19 00:08 UTC, romanblanco requested changes
@pechorin, thank you for continuing in @Zooip's effort!

Besides some minor typo fixes and adjustment, the changes look good :+1:

Would you, please, also update [test-app/](https://github.com/rswag/rswag/tree/master/test-app) with an example of how to use the enhancement and include changes in OpenAPI spec?

2023-03-19 00:08 UTC, romanblanco commented on README.md
> +To avoid conflicts with rspec `included` matcher and other possible intersections like `status` method:
```suggestion
To avoid conflicts with RSpec [`included`](https://github.com/rspec/rspec-rails/blob/40261bb72875c00a6e4a0ca2ac697b660d4e8d9c/spec/support/generators.rb#L18) matcher and other possible intersections like `status` method:
```

2023-03-19 00:08 UTC, romanblanco commented on README.md
> +### Custom :getter option for paramater
```suggestion
### Custom :getter option for parameter
```

2023-03-19 00:08 UTC, romanblanco commented on rswag-specs/spec/rswag/specs/request_factory_spec.rb
> +            it 'builds the query string using getter ethod' do
```suggestion
            it 'builds the query string using getter method' do
```

2023-03-19 00:08 UTC, romanblanco commented on CHANGELOG.md
> +- Add support for :getter parameter option to explicitly define custom param getter method and avoid rspec conflicts with `include` matcher and `status` method
```suggestion
- Add support for `:getter` parameter option to explicitly define custom parameter getter method and avoid RSpec conflicts with `include` matcher and `status` method (https://github.com/rswag/rswag/pull/605)
```

2023-03-19 00:08 UTC, romanblanco commented on rswag-specs/lib/rswag/specs/swagger_formatter.rb
> +                  value[:parameters].each {|p| p.delete(:getter) } # remove service field
@pechorin, I'm wondering — can the `:getter` field be removed in the [`remove_invalid_operation_keys!`](https://github.com/rrebellion/rswag/blob/20fc48b088dbc6b2c35cdd1ee1a1903efd41dc63/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L212) method?

2023-03-19 12:35 UTC, romanblanco commented on rswag-specs/spec/rswag/specs/request_factory_spec.rb
> +            allow(example).to receive(:nums).and_return(nil)
> GitHub Actions / spellchecking 
> Unknown word (nums)

@pechorin please, help addressing these [warnings](https://github.com/rswag/rswag/actions/runs/4349503620/jobs/7828244734?pr=605#step:3:21) too.

2023-03-22 22:21 UTC, pechorin commented
Thanks for response, i will fix all issues within days!

2023-03-29 23:48 UTC, pechorin commented
@romanblanco thanks for cool review, can you check my fixes please? :)

2023-03-31 09:05 UTC, romanblanco approved these changes
LGTM :+1: 

Thank you for the contribution, @pechorin!

2023-03-31 09:06 UTC, merged