feat: make spec folder configurable
rswag/rswag pull request #607
Opened 2023-03-15 07:28 UTC by mohamed-karam

## Problem
The rspec generator only creates files under _spec/requests_ folder. I believe this option can be configurable/.

## Solution
Add option `--spec_path` to the generator command with `requests` as default value.

### Checklist
- [ ] Added tests
- [ ] Changelog updated
- [ *] Added documentation to README.md

### Steps to Test or Reproduce
Just run the generator command with `--spec_path` option.

2023-03-19 13:15 UTC, romanblanco requested changes
@mohamed-karam, thank you for the PR! 

Please add [test](https://github.com/mohamed-karam/rswag/blob/bcc50eb8f46756d8615dcb6fef7ce03f61353a63/rswag-specs/spec/generators/rspec/swagger_generator_spec.rb) covering the `--spec_path` option and update `CHANGELOG.md`

2023-03-20 07:08 UTC, mohamed-karam commented
@romanblanco Done :+1:

2023-03-20 08:07 UTC, romanblanco commented on CHANGELOG.md
> +- Added option --spec_path to the generator command with requests as default value.
```suggestion
- Added option --spec_path to the generator command with requests as default value. (https://github.com/rswag/rswag/pull/607)
```

2023-03-20 09:04 UTC, romanblanco approved these changes
LGTM :+1:

Thank you, @mohamed-karam!

2023-03-20 09:04 UTC, merged