Define extra options for properties
rswag/rswag pull request #721
Opened 2023-12-30 23:18 UTC by IlkhamGaysin

## Problem
It closes https://github.com/rswag/rswag/issues/666

## Solution
Added two more options to allow to use `allPropertiesRequired` and `noAdditionalProperties` options from [json-schema](https://github.com/a-lavis/json-schema)

### This concerns this parts of the OpenAPI Specification:
* [EXAMPLE_LINK TO RELEVANT OPEN API SPECS PAGE](https://spec.openapis.org/oas/v3.1.0#data-types)
* [ANOTHER LINK TO RELEVANT OPEN API SPECS PAGE](https://spec.openapis.org/oas/v3.1.0#schema)

### The changes I made are compatible with:
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

### Related Issues
Links to any related issues.

### Checklist
- [ ] Added tests
- [ ] Changelog updated
- [ ] Added documentation to README.md
- [ ] Added example of using the enhancement into [test-app](https://github.com/rswag/rswag/tree/master/test-app)

### Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

2024-05-28 15:42 UTC, mustmodify commented
@IlkhamGaysin what's the status of this ticket?

2024-06-11 18:31 UTC, IlkhamGaysin commented
@mustmodify updated with master let's see what CI will give us

2024-06-11 18:32 UTC, IlkhamGaysin commented
@romanblanco could you please run the CI

2024-07-15 12:51 UTC, Kulgar commented
Would love to see this one added to the project - can I help?

2024-07-15 22:53 UTC, IlkhamGaysin commented
@Kulgar Could someone merge this? I don't see CI results on this PR.  :/

2024-07-16 04:52 UTC, romanblanco commented
> @romanblanco could you please approve workflow to run on the CI 🍺

Will try to look into why the CI is not running on the PR. Do the tests pass localy?

2024-09-11 12:51 UTC, romanblanco requested changes

2024-09-11 12:51 UTC, romanblanco commented on test-app/spec/integration/blogs_spec.rb
> +      end
These specs are identical

2024-09-11 12:51 UTC, romanblanco commented on rswag-specs/spec/rswag/specs/configuration_spec.rb
> +       it { expect(response).to eq(true) }
Nitpick: indentation

2024-09-23 00:50 UTC, a-lavis commented
@romanblanco I opened #783 to address the above feedback since I don't have write access to this branch.  I hope its helpful - feel free to close if not.

2024-09-24 16:53 UTC, merged